name: Deploy MLflow Server to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Clone the repository (or pull if already cloned)
            cd mlflow-server || git clone https://github.com/MLOpsLab/mlflow-server.git mlflow-server && cd mlflow-server
            git pull origin main
            # Build the Docker image
            docker build -t mlflow-server .
            # Create a custom network (if it doesn't exist)
            docker network create --driver bridge mlops-lab-net || true
            # Stop and remove the existing container if running
            docker stop mlflow || true
            docker rm mlflow || true
            # Run the new container with port mapping
            docker run -d -p 5000:5000 --name mlflow --network mlops-lab-net mlflow-server
