name: Deploy MLflow Server to EC2

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Create project directory
            mkdir -p mlflow-server
            
            # Only clone if the folder is empty
            if [ -z "$(ls -A mlflow-server)" ]; then
              git clone https://github.com/MLOpsLab/mlflow-server.git mlflow-server
            fi  
            
            # Move into the project folder and update it
            cd mlflow-server
            git pull origin main
            
            # Ensure Docker is running
            sudo systemctl start docker

            # Clean previous builds
            docker system prune -f

            # Build Docker image
            docker build -t mlflow-server .

            # Stop and remove existing container
            docker stop mlflow || true
            docker rm mlflow || true

            # Run Docker container with environment variables
            docker run -d \
              --restart=always \
              -p 5000:5000 \
              --name mlflow \
              -e GUNICORN_WORKERS=2 \
              -e GUNICORN_THREADS=1 \
              -e MLFLOW_ARTIFACTS_BUCKET=${{ secrets.MLFLOW_ARTIFACTS_BUCKET }} \
              mlflow-server