name: Deploy MLflow to EC2

on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy setup script to EC2
        run: |
          # Add EC2 host to known_hosts to avoid interactive prompt
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          
          # SCP the script. Adjust path to script if it's not in the root.
          scp ./setup_mlflow.sh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/setup_mlflow.sh
        shell: bash

      - name: Execute setup script on EC2
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "
            set -e;
            chmod +x ~/setup_mlflow.sh;
            echo 'Executing MLflow setup script on EC2...';
            export MLFLOW_S3_BUCKET_NAME_ENV='${{ secrets.MLFLOW_ARTIFACTS_BUCKET }}';
            echo \"S3 Bucket from GitHub Secret (passed as MLFLOW_S3_BUCKET_NAME_ENV): \$MLFLOW_S3_BUCKET_NAME_ENV\";
            cd ~ && ./setup_mlflow.sh;
            echo 'MLflow setup script execution finished.'
          "
        shell: bash

      - name: Clean up SSH key
        # This step is important for security if the runner is reused.
        # webfactory/ssh-agent should handle cleanup, but explicit is fine.
        if: always()
        run: |
          echo "Cleaning up SSH agent"
          ssh-add -D || true # Remove identities from agent
