name: Deploy MLflow to EC2

on:
  push:
    branches: [ develop ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            # Kill any existing MLflow process
            pkill -f "mlflow server" || true
            
            # Create systemd service file for MLflow
            echo "[Unit]
            Description=MLflow Tracking Server
            After=network.target

            [Service]
            User=$USER
            ExecStart=$HOME/.local/bin/mlflow server --host 0.0.0.0 --port 5000 --workers 1
            Restart=on-failure
            RestartSec=5
            StandardOutput=journal
            StandardError=journal

            [Install]
            WantedBy=multi-user.target" > /tmp/mlflow.service
            
            # Set up systemd service
            sudo mv /tmp/mlflow.service /etc/systemd/system/mlflow.service
            sudo systemctl daemon-reload
            sudo systemctl enable mlflow.service
            sudo systemctl restart mlflow.service
            
            # Quick check to verify service is running
            sleep 5
            systemctl status mlflow.service